# Generated by Django 4.2.30 on 2026-07-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_blockedslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='slot_duration_minutes',
            field=models.IntegerField(choices=[(30, '30 Dakika'), (60, '1 Saat')], default=30),
        ),
    ]
