# Generated by Django 4.2.30 on 2026-07-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_barber_slot_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='barber_logos/'),
        ),
    ]
