# Generated by Django 4.2.30 on 2026-07-21 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_shop_barber_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Randevu', 'verbose_name_plural': 'Randevular'},
        ),
        migrations.AlterModelOptions(
            name='barber',
            options={'verbose_name': 'Berber / Personel', 'verbose_name_plural': 'Berberler / Personeller'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Haftalık Şablon (Çalışma Saati)', 'verbose_name_plural': 'Haftalık Şablonlar'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Dükkan', 'verbose_name_plural': 'Dükkanlar'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Bekliyor'), ('CONFIRMED', 'Onaylandı'), ('CANCELLED', 'İptal Edildi')], default='CONFIRMED', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='slot_duration_minutes',
            field=models.IntegerField(choices=[(30, '30 Dakika'), (60, '1 Saat')], default=30, verbose_name='Randevu Periyodu'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_off_day',
            field=models.BooleanField(default=False, verbose_name='Kapalı Gün'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_shop', to=settings.AUTH_USER_MODEL, verbose_name='Patron (Dükkan Sahibi)'),
        ),
    ]
