# Generated by Django 4.2.30 on 2026-07-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_options_alter_barber_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='slot_duration_minutes',
            field=models.IntegerField(choices=[(30, '30 Dakika'), (60, '1 Saat')], default=60, verbose_name='Randevu Periyodu'),
        ),
    ]
