# Generated by Django 4.2.30 on 2026-07-21 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_barber_slot_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Toplam Tutar (TL)'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hizmet Adı')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fiyat (TL)')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='Süre (Dakika)')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Berber')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='appointments.service', verbose_name='Seçilen Hizmetler'),
        ),
    ]
